import { test } from 'node:test';
import assert from 'node:assert/strict';
import { OPERATIONS_KEY, createOperationsStore, createEmptyOperations, validateOperations, stockBalance, stockStatus, serviceStatus, summarizeOperations, todayInTimeZone } from '../src/lib/operations.ts';
class MemoryStorage { value = null; failWrites = false; getItem(key) { assert.equal(key, OPERATIONS_KEY); return this.value; } setItem(key, value) { assert.equal(key, OPERATIONS_KEY); if (this.failWrites) throw new Error('QuotaExceededError'); this.value = value; } }
const item = { id: 'seed', name: 'Seed', unit: 'kg', reorderThreshold: 3 };
const machine = { id: 'pump', name: 'Pump', meter: 100, meterUnit: 'hours', serviceInterval: 50, serviceIntervalDays: 30, lastServiceDate: '2026-09-01', lastServiceMeter: 50 };
const movement = (id, type, quantity) => ({ id, itemId: 'seed', type, quantity, date: '2026-10-01', note: type === 'adjust' ? 'Count correction' : '' });
function fixture() { const data = createEmptyOperations(); data.inventory.push(item); data.equipment.push(machine); return data; }
test('blank first use is detached and does not write sample records', () => { const storage = new MemoryStorage(); const store = createOperationsStore(storage); const a = store.load(); a.settings.farmName = 'Changed'; assert.equal(store.load().settings.farmName, ''); assert.equal(storage.value, null); });
test('single commit contains previous data; quota failure preserves exact stored bytes', () => { const storage = new MemoryStorage(); const store = createOperationsStore(storage); const saved = store.save(fixture(), 0); assert.equal(saved.revision, 1); assert.equal(JSON.parse(storage.value).previous.revision, 0); const before = storage.value; storage.failWrites = true; assert.throws(() => store.save(saved, 1), /Could not save/); assert.equal(storage.value, before); });
test('stale tabs cannot overwrite a newer revision', () => { const storage = new MemoryStorage(); const a = createOperationsStore(storage); const b = createOperationsStore(storage); const stale = b.load(); a.save(fixture(), 0); const before = storage.value; assert.throws(() => b.save(stale, 0), /another tab/); assert.equal(storage.value, before); });
test('corrupt JSON and unsupported current versions are never overwritten', () => { for (const value of ['{broken', JSON.stringify({ current: { ...fixture(), schemaVersion: 99 }, previous: null })]) { const storage = new MemoryStorage(); storage.value = value; const store = createOperationsStore(storage); assert.throws(() => store.load()); assert.throws(() => store.save(fixture(), 0)); assert.throws(() => store.importJSON(JSON.stringify(fixture()), 0)); assert.equal(storage.value, value); assert.equal(store.exportRaw(), value); } });
test('validated export/import round trip and invalid import leaves bytes unchanged', () => { const storage = new MemoryStorage(); const store = createOperationsStore(storage); store.save(fixture(), 0); const exported = store.exportJSON(); assert.deepEqual(store.previewImport(exported), store.load()); const before = storage.value; for (const bad of ['{', JSON.stringify({ ...fixture(), schemaVersion: 2 }), JSON.stringify({ ...fixture(), inventory: [item, item] }), JSON.stringify({ ...fixture(), movements: [movement('bad', 'use', 1)] })]) { assert.throws(() => store.importJSON(bad, 1)); assert.equal(storage.value, before); } const target = createOperationsStore(new MemoryStorage()); assert.deepEqual(target.importJSON(exported, 0), store.load()); });
test('explicit backup restore advances revision and allows toggling to prior good data', () => { const store = createOperationsStore(new MemoryStorage()); const a = store.save(fixture(), 0); a.settings.farmName = 'New'; store.save(a, 1); assert.equal(store.hasBackup(), true); assert.equal(store.restoreBackup(2).settings.farmName, ''); assert.equal(store.load().revision, 3); assert.equal(store.restoreBackup(3).settings.farmName, 'New'); });
test('corrupt current can explicitly recover previous data without losing corruption evidence', () => { const storage = new MemoryStorage(); const store = createOperationsStore(storage); store.save(fixture(), 0); const envelope = JSON.parse(storage.value); envelope.current.inventory[0].reorderThreshold = -1; storage.value = JSON.stringify(envelope); const corrupt = storage.value; assert.throws(() => store.load()); assert.equal(store.hasBackup(), true); assert.throws(() => store.restoreBackup(1)); assert.equal(store.restoreBackup(null).revision, 1); assert.equal(JSON.parse(storage.value).recoveryEvidence, corrupt); const recovered = store.load(); store.save(recovered, recovered.revision); assert.equal(JSON.parse(storage.value).recoveryEvidence, corrupt); });
test('stock math handles receive, use, signed adjustment and thresholds', () => { const data = fixture(); data.movements = [movement('a', 'receive', 10), movement('b', 'use', 7), movement('c', 'adjust', -1)]; validateOperations(data); assert.equal(stockBalance(data, 'seed'), 2); assert.equal(stockStatus(data, 'seed'), 'low'); data.movements.push(movement('d', 'use', 2)); assert.equal(stockStatus(data, 'seed'), 'empty'); data.movements.push(movement('e', 'adjust', -1)); assert.throws(() => validateOperations(data), /negative/); });
test('stock/service histories append only; meter cannot move backward', () => { const store = createOperationsStore(new MemoryStorage()); const data = fixture(); data.movements.push(movement('a', 'receive', 10)); data.services.push({ id: 's', equipmentId: 'pump', date: '2026-10-01', meter: 100, note: '' }); const saved = store.save(data, 0); const changed = structuredClone(saved); changed.movements[0].quantity = 20; assert.throws(() => store.save(changed, 1), /append-only/); changed.movements = saved.movements; changed.services = []; assert.throws(() => store.save(changed, 1), /append-only/); changed.services = saved.services; changed.equipment[0].meter = 99; assert.throws(() => store.save(changed, 1)); });
test('service status uses latest record, meter and calendar, with exact due boundaries', () => { const data = fixture(); assert.equal(serviceStatus(data, 'pump', '2026-09-30').due, true); data.equipment[0] = { ...machine, meter: 99 }; assert.equal(serviceStatus(data, 'pump', '2026-09-30').due, false); assert.equal(serviceStatus(data, 'pump', '2026-10-01').due, true); data.equipment[0].meter = 100; data.services.push({ id: 's1', equipmentId: 'pump', date: '2026-10-01', meter: 100, note: 'Oil changed' }); const status = serviceStatus(data, 'pump', '2026-10-01'); assert.equal(status.due, false); assert.equal(status.remainingMeter, 50); assert.equal(status.nextServiceDate, '2026-10-31'); assert.equal(status.daysRemaining, 30); });
test('validation rejects invalid date, nonfinite, foreign references and reversed service history', () => { for (const mutate of [d => { d.equipment[0].meter = Infinity; }, d => { d.activities.push({ id: 'a', title: 'Water', date: '2026-02-30', dueDate: '2026-03-01', completed: false, note: '' }); }, d => { d.movements.push({ ...movement('m', 'receive', 1), itemId: 'missing' }); }, d => { d.services.push({ id: 's1', equipmentId: 'pump', date: '2026-09-10', meter: 80, note: '' }, { id: 's2', equipmentId: 'pump', date: '2026-09-09', meter: 90, note: '' }); }]) { const d = fixture(); d.equipment = [{ ...machine }]; mutate(d); assert.throws(() => validateOperations(d)); } });
test('time zone dates and deterministic activity summary', () => { const instant = new Date('2026-09-30T22:30:00Z'); assert.equal(todayInTimeZone('Africa/Nairobi', instant), '2026-10-01'); assert.equal(todayInTimeZone('America/New_York', instant), '2026-09-30'); const d = createEmptyOperations(); d.activities = [{ id: 'a', title: 'Water', date: '2026-09-01', dueDate: '2026-09-30', completed: false, note: '' }, { id: 'b', title: 'Feed', date: '2026-10-01', dueDate: '2026-10-01', completed: true, note: '' }]; const summary = summarizeOperations(d, '2026-10-01'); assert.equal(summary.openActivities, 1); assert.equal(summary.overdueActivities, 1); assert.equal(summary.dueToday, 0); });
test('storage unavailable errors are actionable and do not masquerade as empty records', () => { const store = createOperationsStore({ getItem() { throw new Error('Denied'); }, setItem() {} }); assert.throws(() => store.load(), /Could not read/); });
test('unrecorded stock and unscheduled equipment remain distinct from low stock and due service', () => { const d = fixture(); d.equipment = [{ ...machine, serviceInterval: null, serviceIntervalDays: null }]; validateOperations(d); assert.equal(stockStatus(d, 'seed'), 'unrecorded'); assert.equal(summarizeOperations(d, '2026-10-01').lowStock, 0); assert.equal(serviceStatus(d, 'pump', '2026-10-01').scheduleSet, false); assert.equal(serviceStatus(d, 'pump', '2026-10-01').due, false); });
test('adjustments require reasons and used item units cannot change', () => { const d = fixture(); d.movements = [movement('m', 'receive', 10), { ...movement('a', 'adjust', -1), note: '' }]; assert.throws(() => validateOperations(d), /cannot be blank/); d.movements.pop(); const store = createOperationsStore(new MemoryStorage()); const saved = store.save(d, 0); saved.inventory[0].unit = 'bags'; assert.throws(() => store.save(saved, 1), /unit/); });
test('change observed between initial read and commit aborts without writing', () => { const prior = { current: fixture(), previous: null }; let reads = 0; let writes = 0; const store = createOperationsStore({ getItem() { return JSON.stringify({ ...prior, current: { ...prior.current, revision: reads++ > 0 ? 1 : 0 } }); }, setItem() { writes++; } }); assert.throws(() => store.save(fixture(), 0), /another tab/); assert.equal(writes, 0); });
test('backup unavailable and quota failure during restore preserve data', () => { const storage = new MemoryStorage(); const store = createOperationsStore(storage); assert.throws(() => store.restoreBackup(null), /No previous/); store.save(fixture(), 0); const before = storage.value; storage.failWrites = true; assert.throws(() => store.restoreBackup(1), /Could not save/); assert.equal(storage.value, before); });
test('six decimal precision, currency codes and service calendar bounds are validated', () => { const d = fixture(); d.movements.push(movement('x', 'receive', 1.0000001)); assert.throws(() => validateOperations(d), /six decimal/); d.movements = []; d.equipment = [{ ...machine, lastServiceDate: '9999-12-31' }]; assert.throws(() => validateOperations(d), /9999/); d.equipment = []; d.settings.currency = 'ZZZ'; assert.throws(() => validateOperations(d), /currency/); });
test('explicit recovery import preserves malformed raw data and rejects stale evidence', () => { const storage = new MemoryStorage(); storage.value = '{broken'; const store = createOperationsStore(storage); const json = JSON.stringify(fixture()); assert.throws(() => store.recoverImportJSON(json, '{different'), /changed/); const restored = store.recoverImportJSON(json, '{broken'); assert.equal(restored.revision, 1); assert.equal(JSON.parse(storage.value).recoveryEvidence, '{broken'); assert.equal(store.hasBackup(), false); assert.throws(() => store.recoverImportJSON(json, storage.value), /valid/); });
test('six-decimal stock arithmetic stays exact across fractional movements', () => { const d = fixture(); d.movements = [movement('a', 'receive', 0.1), movement('b', 'receive', 0.2), movement('c', 'use', 0.3), movement('d', 'receive', 0.000001)]; validateOperations(d); assert.equal(stockBalance(d, 'seed'), 0.000001); d.movements.push(movement('e', 'use', 0.000001)); validateOperations(d); assert.equal(stockBalance(d, 'seed'), 0); });
test('old tab rejects save and import after backup recovery reuses its revision', () => {
  const storage = new MemoryStorage(); const staleTab = createOperationsStore(storage);
  const stale = staleTab.save(fixture(), 0); assert.equal(stale.revision, 1);
  const envelope = JSON.parse(storage.value); envelope.current.inventory[0].reorderThreshold = -1; storage.value = JSON.stringify(envelope);
  const recoveryTab = createOperationsStore(storage); assert.throws(() => recoveryTab.load());
  const restored = recoveryTab.restoreBackup(null); assert.equal(restored.revision, stale.revision);
  const recoveredRaw = storage.value;
  assert.throws(() => staleTab.save(stale, stale.revision), /recovered/);
  assert.throws(() => staleTab.importJSON(JSON.stringify(stale), stale.revision), /recovered/);
  assert.equal(storage.value, recoveredRaw);
  const refreshed = staleTab.load(); refreshed.settings.farmName = 'After reload'; assert.equal(staleTab.save(refreshed, refreshed.revision).revision, 2);
});
test('old tab rejects save after recovery import reuses its revision', () => {
  const storage = new MemoryStorage(); const staleTab = createOperationsStore(storage); const stale = staleTab.save(fixture(), 0);
  storage.value = '{broken'; const recoveryTab = createOperationsStore(storage);
  const restored = recoveryTab.recoverImportJSON(JSON.stringify(fixture()), '{broken'); assert.equal(restored.revision, stale.revision);
  const recoveredRaw = storage.value; assert.throws(() => staleTab.save(stale, stale.revision), /recovered/); assert.equal(storage.value, recoveredRaw);
  staleTab.exportJSON(); staleTab.exportRaw(); staleTab.hasBackup(); assert.throws(() => staleTab.save(stale, stale.revision), /recovered/);
});
